name: breast-cancer-env

channels:
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==3.7.0
      - cloudpickle==3.1.2
      - numpy==2.3.5
      - pandas==2.3.3
      - psutil==7.1.3
      - scikit-learn==1.6.1
      - scipy==1.16.3